<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.



function ajaxpagination_theme($existing, $type, $theme, $path) {
   return array(
    'test_twig' => array(
    'variables' => array('test_var' => NULL, 'page_content_var' => NULL,   'id' => NULL),
    ),
  );
}


 
function ajaxpagination_page_build(&$page) {
  $path = drupal_get_path('module', 'ajaxpagination');
  $page['#attached']['css'][$path . '/css/ajaxpagination.css'] = array('every_page' => TRUE);
   
 // if (\Drupal::config('simple_dialog.settings')->get('js_all')) {
  //  simple_dialog_attach_js($page, TRUE);
  //}
}
 


function ajaxpagination_element_info_alter(array &$page)  {
   $page['#attached']['library'][] = 'ajaxpagination/global-styling';
 }
 
 function ajaxpagination_init_method(){
    //$page['#attached']['library'][] = 'ajaxpagination/ajaxpagination.global-styling';
    drupal_add_js(drupal_get_path('module', 'ajaxpagination') . '/js/base.js');
 }
  
 
 function ggggggg(){
     echo ("3; ");
 }
 
 
    
 
  
 
 echo "2; ";
 //exit("ddd");
 //ajax_get_s("ddddddddddddddddd");
 
  */
 